export const DEFAULT_LANGUAGE_TOKEN = 'TRANSLATE_DEFAULT_LANGUAGE';
export const LANGUAGES = 'TRANSLATE_LANGUAGES';
export const ENABLE_MISSING_TRANSLATION_LOGGING = 'TRANSLATE_ENABLE_MISSING_TRANSLATION_LOGGING';
export const MISSING_TRANSLATION_HANDLER = 'TRANSLATE_MISSING_TRANSLATION_HANDLER';
